In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder

<h5>Data Preparation</h5>

In [2]:
## Reading the dataset
df = pd.read_csv('data/diabetes.csv')

## Train and Target dataset
train, target = df[['Glucose', 'BMI']].values, df['Outcome'].values

## Encoding
le = LabelEncoder()
target = le.fit_transform(target)

## Splitting the data
X_train, X_test, y_train, y_test = train_test_split(train, target, random_state = 42)

<h5>Working with an individual data point</h5>

Set k value and take one data point from test dataset

In [27]:
k = 5
data_point = X_test[[0]]
data_point

array([[98., 34.]])

Calculate the Euclidean distances 

In [28]:
distances = ((data_point - X_train) ** 2).sum(axis = 1)
distances.shape

(576,)

Get indexes of the lowest distances

In [94]:
indexes = np.argsort(distances)
lowest_distances_index = indexes[:k]
lowest_distances_index

array([459, 135, 487, 546,  10], dtype=int64)

Calling the corresponding indexes from train target dataset

In [97]:
y_train[lowest_distances_index]

array([0, 0, 0, 0, 1])

Applying KNN method to make a prediction on the chosen data point

In [31]:
knc = KNeighborsClassifier(k)
knc.fit(X_train, y_train)

KNeighborsClassifier()

In [93]:
## 80 percent probabilty to be class 0
knc.predict_proba(data_point)

array([[0.8, 0.2]])